# Generated by Django 4.2.5 on 2024-05-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Test_paper_subject1",
            fields=[
                ("q_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ques", models.CharField(max_length=100)),
                ("a", models.CharField(max_length=50)),
                ("b", models.CharField(max_length=50)),
                ("c", models.CharField(max_length=50)),
                ("d", models.CharField(max_length=50)),
                ("ans", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Test_paper_subject2",
            fields=[
                ("q_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ques", models.CharField(max_length=100)),
                ("a", models.CharField(max_length=50)),
                ("b", models.CharField(max_length=50)),
                ("c", models.CharField(max_length=50)),
                ("d", models.CharField(max_length=50)),
                ("ans", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Test_paper_subject3",
            fields=[
                ("q_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ques", models.CharField(max_length=100)),
                ("a", models.CharField(max_length=50)),
                ("b", models.CharField(max_length=50)),
                ("c", models.CharField(max_length=50)),
                ("d", models.CharField(max_length=50)),
                ("ans", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="online_test.user",
                    ),
                ),
                ("fathers_name", models.CharField(default="", max_length=30)),
                ("mothers_name", models.CharField(default="", max_length=30)),
                ("phone", models.CharField(default="", max_length=10)),
                ("email", models.CharField(default="", max_length=30)),
                ("address", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Test_history",
            fields=[
                (
                    "test_id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("subject", models.CharField(default="", max_length=25)),
                ("total", models.IntegerField()),
                ("correct", models.IntegerField()),
                ("wrong", models.IntegerField()),
                ("percentage", models.IntegerField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_test.user",
                    ),
                ),
            ],
        ),
    ]
