# Generated by Django 4.2.5 on 2024-02-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("online_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.ForeignKey(
                max_length=20,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="online_test.user",
            ),
        ),
    ]
