# Generated by Django 4.2.5 on 2024-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test_paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_id", models.IntegerField()),
                ("ques", models.CharField(max_length=100)),
                ("a", models.CharField(max_length=20)),
                ("b", models.CharField(max_length=20)),
                ("c", models.CharField(max_length=20)),
                ("d", models.CharField(max_length=20)),
                ("ans", models.CharField(max_length=2)),
            ],
        ),
    ]
